"""Generate TFT_eSPI smooth fonts (Processing .vlw format) from the Assistant TTFs.

    python tools/make_fonts.py      (needs: pip install freetype-py)

Writes src/native/TftFonts.h with one PROGMEM array per size. Each font only
carries the glyphs the clock face uses, to keep flash use small.
"""
import os
import struct

import freetype

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "native", "TftFonts.h")

HEBREW = "".join(chr(c) for c in range(0x05D0, 0x05EB)) + "׳״־"
DIGITS = "0123456789"

# name, weight, pixel size, characters
FONTS = [
    ("font_time52", 800, 52, DIGITS + ":"),
    ("font_date30", 700, 30, DIGITS + "/"),
    ("font_heb25", 700, 25, HEBREW + DIGITS + " '\":"),
    ("font_heb21", 600, 21, HEBREW + DIGITS + " '\"°"),
    ("font_heb18", 700, 18, HEBREW + DIGITS + " '\":()-.·,"),
    ("font_card27", 700, 27, DIGITS + ":"),
    ("font_small13", 700, 13, HEBREW + DIGITS + " '\":()-.·,°/"),
]


def vlw(ttf, size, chars):
    face = freetype.Face(ttf)
    face.set_pixel_sizes(0, size)
    glyphs = []
    for ch in sorted(set(chars), key=ord):
        if face.get_char_index(ord(ch)) == 0:
            print(f"  warning: {os.path.basename(ttf)} has no glyph for U+{ord(ch):04X}")
            continue
        face.load_char(ch, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        g = face.glyph
        bm = g.bitmap
        rows = [bytes(bm.buffer[r * bm.pitch:r * bm.pitch + bm.width]) for r in range(bm.rows)]
        glyphs.append((ord(ch), bm.rows, bm.width, g.advance.x >> 6, g.bitmap_top, g.bitmap_left, b"".join(rows)))
    ascent = face.size.ascender >> 6
    descent = -(face.size.descender >> 6)
    data = struct.pack(">6i", len(glyphs), 11, size, 0, ascent, descent)
    for code, h, w, adv, dy, dx, _ in glyphs:
        data += struct.pack(">7i", code, h, w, adv, dy, dx, 0)
    for *_, bitmap in glyphs:
        data += bitmap
    return data, len(glyphs)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    parts = ["// Generated by tools/make_fonts.py from Assistant (SIL Open Font License). Do not edit.",
             "#pragma once", "#include <Arduino.h>", ""]
    total = 0
    for name, weight, size, chars in FONTS:
        data, n = vlw(os.path.join(HERE, "fonts", f"Assistant-{weight}.ttf"), size, chars)
        total += len(data)
        print(f"{name}: {n} glyphs, {len(data)} bytes")
        body = ",".join(str(b) for b in data)
        parts.append(f"const uint8_t {name}[] PROGMEM = {{{body}}};")
    parts.append("")
    open(OUT, "w", encoding="utf-8").write("\n".join(parts))
    print(f"total {total} bytes -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
