"""Render the clock-face icons (same drawings as the design mockup) into 8-bit
alpha bitmaps for the TFT.

    python tools/make_icons.py

Uses headless Microsoft Edge to rasterise the SVG strokes and ffmpeg to read the
pixels back, then writes src/native/TftIcons.h.
"""
import os
import subprocess
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "native", "TftIcons.h")
EDGE = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
FFMPEG = os.path.expandvars(r"%LOCALAPPDATA%\ffmpegio\ffmpeg-downloader\ffmpeg\bin\ffmpeg.exe")

ICONS = {
    "dawn": '<path d="M3 18h18M7 18a5 5 0 0 1 10 0M12 8v2M5.5 11.5l1.4 1.4M18.5 11.5l-1.4 1.4"/>',
    "sunrise": '<path d="M3 19h18M7 19a5 5 0 0 1 10 0M12 4v7M9 7l3-3 3 3"/>',
    "shema": '<path d="M4 5h5a3 3 0 0 1 3 3v11a2 2 0 0 0-2-2H4zM20 5h-5a3 3 0 0 0-3 3v11a2 2 0 0 1 2-2h6z"/>',
    "tefila": '<path d="M3 20h18M3 20V7h18v13M3 11.3h18M3 15.6h18M8 7v4.3M15 7v4.3M11.5 11.3v4.3M18 11.3v4.3M5.5 15.6V20M14 15.6V20"/>',
    "noon": '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',
    "plag": '<path d="M3 19h18M8 19a4 4 0 0 1 8 0M12 9v2M6 13l1.4 1M18 13l-1.4 1M16 5l-3 2M8 5l3 2"/>',
    "sunset": '<path d="M3 19h18M7 19a5 5 0 0 1 10 0M12 4v7M9 8l3 3 3-3"/>',
    "stars": '<path d="M9 4l1.3 2.7 3 .4-2.2 2.1.5 3-2.6-1.4-2.6 1.4.5-3L4.7 7.1l3-.4zM17 13l.8 1.7 1.9.3-1.4 1.3.3 1.9-1.6-.9-1.6.9.3-1.9-1.4-1.3 1.9-.3zM5 17.5h.01M19 7h.01"/>',
    "candles": '<path d="M8 21v-9h3v9zM13 21v-9h3v9zM5 21h14M9.5 9c-1-1-.8-2.4 0-3.5.8 1.1 1 2.5 0 3.5zM14.5 9c-1-1-.8-2.4 0-3.5.8 1.1 1 2.5 0 3.5z"/>',
    "havdala": '<path d="M4 18h16M6 18l2-8h8l2 8M12 10V4M9 6l3-2 3 2"/>',
    "sukkah": '<path d="M4 20V11h16v9M2 11h20M4 8l2 3M8 8l2 3M12 8l2 3M16 8l2 3M10 20v-5h4v5"/>',
    "moon": '<path d="M19 14.5A7.5 7.5 0 1 1 9.5 5a6 6 0 0 0 9.5 9.5z"/>',
    "rain": '<path d="M12 3c3 4.2 5 7.2 5 10a5 5 0 0 1-10 0c0-2.8 2-5.8 5-10z"/>',
    "wheat": '<path d="M12 21V7M12 7c-1.8-.9-2.8-2.6-2.8-4.5 1.8 0 2.8 1.7 2.8 4.5zM12 7c1.8-.9 2.8-2.6 2.8-4.5-1.8 0-2.8 1.7-2.8 4.5zM12 12c-2-1-3.6-2.8-3.6-5 2 0 3.6 2 3.6 5zM12 12c2-1 3.6-2.8 3.6-5-2 0-3.6 2-3.6 5zM12 17c-2-1-3.6-2.8-3.6-5 2 0 3.6 2 3.6 5zM12 17c2-1 3.6-2.8 3.6-5-2 0-3.6 2-3.6 5z"/>',
    "fast": '<path d="M6 3h12M6 21h12M7 3c0 5 10 5 10 9s-10 4-10 9M17 3c0 5-10 5-10 9s10 4 10 9"/>',
    "therm": '<path d="M10 13.5V5a2 2 0 0 1 4 0v8.5a4 4 0 1 1-4 0zM12 9v7"/>',
    # control bar
    "menu": '<path d="M4 7h16M4 12h16M4 17h16"/>',
    "dimmer": '<circle cx="12" cy="12" r="4"/><path d="M8 12h8"/>',
    "brighter": '<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M2 12h2M20 12h2M8 12h8M12 8v8"/>',
    "close": '<path d="M6 6l12 12M18 6L6 18"/>',
}
SIZES = [18, 20, 24]
CELL = 32


def main():
    names = list(ICONS)
    w, h = CELL * len(names), CELL * len(SIZES)
    svgs = []
    for row, size in enumerate(SIZES):
        for col, name in enumerate(names):
            svgs.append(
                f'<svg style="position:absolute;left:{col * CELL}px;top:{row * CELL}px" width="{size}" height="{size}" '
                f'viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1.8" stroke-linecap="round" '
                f'stroke-linejoin="round">{ICONS[name]}</svg>')
    html = f'<html><body style="margin:0;background:#000;width:{w}px;height:{h}px">{"".join(svgs)}</body></html>'
    tmp = tempfile.mkdtemp()
    page, shot, raw = (os.path.join(tmp, n) for n in ("icons.html", "icons.png", "icons.gray"))
    open(page, "w").write(html)
    subprocess.run([EDGE, "--headless", "--disable-gpu", "--force-device-scale-factor=1", "--hide-scrollbars",
                    f"--window-size={w},{h}", f"--screenshot={shot}", "file:///" + page.replace("\\", "/")],
                   capture_output=True, timeout=60)
    subprocess.run([FFMPEG, "-loglevel", "error", "-y", "-i", shot, "-pix_fmt", "gray", "-f", "rawvideo", raw], check=True)
    pix = open(raw, "rb").read()

    lines = ["// Generated by tools/make_icons.py. Do not edit.", "#pragma once", "#include <Arduino.h>", "",
             "struct TftIcon { uint8_t w, h; const uint8_t *alpha; };", ""]
    for row, size in enumerate(SIZES):
        for col, name in enumerate(names):
            data = bytearray()
            for y in range(size):
                start = (row * CELL + y) * w + col * CELL
                data += pix[start:start + size]
            lines.append(f"const uint8_t icon_{name}_{size}_a[] PROGMEM = {{{','.join(map(str, data))}}};")
            lines.append(f"const TftIcon icon_{name}_{size} = {{{size}, {size}, icon_{name}_{size}_a}};")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print(f"{len(names)} icons x {len(SIZES)} sizes -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
